### ISSUE TITLE
Funktioniert leider nicht unter Jameica 2.6.2

### ISSUE THREAD

**Issue by cbuhmann** [littleyoda/hibiscus.airplus#2]
Wie angegeben installiert und eingerichtet. Unter "Synchronisierungsoptionen" erscheint lediglich der Haken bei den Gegenbuchungen, sonst keine Möglichkeit Login-Daten zu vergeben.
Script startet und macht nichts.

**Comment by littleyoda** [comment]
Welche Hibiscus-Version nutzt du?
Ist bei Zugangsverfahren "Airplus" ausgewählt?

**Comment by cbuhmann** [comment]
Ok. Danke für den Hinweis. Das Plugin war aus irgendeinem Grund nicht
korrekt geladen.
Manuell entfernt, manuell neu installiert.
Dann war auch das Zugangsverfahren Airplus verfügbar.
Jetzt geht's.
Danke und schönen Abend.


2015-05-26 19:10 GMT+02:00 Sven <notifications@github.com>:
