### ISSUE TITLE
airplus connection refused

### ISSUE THREAD

**Issue by Massimo-B** [littleyoda/hibiscus.airplus#3]
Hi, trying to synchronize Airplus the connection is failed:

org.apache.http.conn.HttpHostConnectException: Connect to portal.airplus.com:443 [portal.airplus.com/193.254.30.57] failed: Connection refused

Maybe the system proxy settings are not considered, while the rest of hibiscus is working fine with the system proxy settings.

**Comment by littleyoda** [comment]
Proxy-Support ist nachgerüstet.
Falls es bei dir funktioniert, rüste ich es bei den anderen Plugins nach

**Comment by littleyoda** [comment]
Leider habe ich noch keine Rückmeldung, ob es jetzt funktioniert.

**Comment by Massimo-B** [comment]
Getestet und funktioniert. Vielen Dank.
